behavior:
  ros__parameters:
    frequency: 10.0 # {double} [Hz]
    plan_frequency: 2.0 # {double} [Hz]

controller:
  ros__parameters:
    frequency: 20.0 # {double} [Hz]
    lookahead_distance: 0.3 # {double} [m]
    lookahead_lin_vel: 0.5 # {double} [m/s]
    stop_thres: 0.1 # {double} [m]
    max_lin_vel: 0.5 # {double} [m/s]
    max_ang_vel: 2.0 # {double} [rad/s]

planner:
  ros__parameters:
    max_access_cost: 100 # {int} []
